# Generated by Django 5.1.7 on 2025-03-25 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('auto', 'ავტომატიკა'), ('manual', 'მექანიკა'), ('tiptronic', 'ტიპტრონიკი')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('fuel_capacity', models.PositiveIntegerField()),
                ('photo1', models.ImageField(upload_to='cars/')),
                ('photo2', models.ImageField(upload_to='cars/')),
                ('photo3', models.ImageField(upload_to='cars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
